import pytest
import requests
from fixtures.user_fixtures import create_test_user, create_and_delete_test_user
from fixtures.payment_fixture import create_test_payment, create_and_delete_test_payment

